// Builds the client from src/client.js:
//
//   dist/client/index.js    ESM for the npm package
//   dist/client/index.d.ts  types for the npm package
//   dist/client/worker.js   the minified IIFE the Worker serves at /ogshot.js, as a module
//                           exporting the source string
//
// Run by wrangler before dev and deploy (build.command), by npm before test and pack.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";

const banner = "// ogshot client. https://github.com/jclusso/ogshot";

const esm = await build({
  entryPoints: ["src/client.js"],
  bundle: true,
  format: "esm",
  target: "es2020",
  write: false,
  banner: { js: banner },
});

const iife = await build({
  stdin: { contents: 'import { ogshot } from "./client.js"; ogshot();', resolveDir: "src" },
  bundle: true,
  format: "iife",
  target: "es2020",
  minify: true,
  write: false,
  banner: { js: banner },
});

mkdirSync("dist/client", { recursive: true });
writeFileSync("dist/client/index.js", esm.outputFiles[0].text);
writeFileSync(
  "dist/client/index.d.ts",
  `/**
 * Warms the cache for the page's og:image, or with \`?ogshot-preview\` in the URL swaps the
 * body for the OG template at 1200x630. Call once per page load.
 */
export function ogshot(): void;
`,
);
writeFileSync(
  "dist/client/worker.js",
  `// Generated by scripts/build-client.js. Do not edit.\nexport const clientScript = ${JSON.stringify(iife.outputFiles[0].text)};\n`,
);
console.log(`Wrote dist/client (script: ${iife.outputFiles[0].text.length} bytes)`);
